---
#################################
# Project
#################################

project_id: cassandra
java_version: 8

#################################
# Application layer
#################################


#################################
# Database layer
#################################

#################################
# Application configuration
#################################
