---
java_download: http://download.oracle.com/otn-pub/java/jdk/8u25-b17/jdk-8u25-linux-x64.tar.gz
java_name: jdk1.8.0_25
download_folder: /usr/src
java_archive: "{{download_folder}}/{{java_name}}.tar.gz"
java_folder: /usr/lib/jvm
java_alias: java-8-jdk-oracle
