---
- name: Monitoring node
  hosts: localhost
  connection: local
  roles:
    - role: aws
      ec2_tags:
        Name: "smart-monitoring"
      ec2_region: eu-central-1
      ec2_image_id: ami-26c43149
      ec2_key_name: "eu-smartcat"
      ec2_security_group: "anomaly-stack"
      ec2_instance_type: m4.xlarge
      ec2_count: 1
      ec2_group: smart-monitoring

- name: Setup instance
  hosts: smart-monitoring
  gather_facts: False
  tags: ['aws-setup', 'aws-start']
  remote_user: ubuntu
  become: yes
  become_method: sudo
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - docker-common
    - influxdb-docker
    - elk-docker
    - grafana-docker
    - riemann-docker
