---
  - name: Copy reporter config fat jar
    copy: src=reporter-config2-custom.jar
      dest={{ cassandra_lib_location }}/reporter-config2-custom.jar
      mode=0755 owner=cassandra group=cassandra
    notify: Restart cassandra service

  - name: Copy reporter config
    template: src=metrics-config.yaml.j2 dest={{ cassandra_lib_location }}/metrics-config.yaml
      mode=0755 owner=cassandra group=cassandra
    notify: Restart cassandra service

  - name: Ensure configuration exists in cassandra-env.sh
    lineinfile: dest={{ cassandra_env_location}}/{{cassandra_env_file }} state=present mode=0644
      regexp='^JVM_OPTS="$JVM_OPTS -Dcassandra.metricsReporterConfigFile=metrics-config.yaml"'
      line='JVM_OPTS="$JVM_OPTS -Dcassandra.metricsReporterConfigFile=metrics-config.yaml"'
    notify: Restart cassandra service

  - meta: flush_handlers
