---
  - name: Update APT cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Install common packages
    apt: name={{ item }} state=present
    with_items:
      - emacs23-nox
      - less
      - tree
      - curl
      - ntp

  - name: Create downloads directory
    file: path={{ downloads_directory }} owner=root group=root state=directory
